spring:
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/easyproject?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=true
      username: root
      password: root
  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.java.pojo

server:
  port: 9000

